affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: liqo.io/type
              operator: DoesNotExist
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.200.0.0/16
