services:
  proxy:
    image: rpardini/docker-registry-proxy:0.6.5
    container_name: liqo_registry_proxy
    ports:
      - "3128:3128"
    environment:
      ENABLE_MANIFEST_CACHE: "true"
    volumes:
      - ./docker_mirror_cache:/docker_mirror_cache
      - ./docker_mirror_certs:/ca
    restart: unless-stopped
    networks:
      - virtual-cluster

networks:
  virtual-cluster:
    external: true
