apiVersion: networking.liqo.io/v1beta1
kind: FirewallConfiguration
metadata:
  labels:
    liqo.io/managed: "true"
    networking.liqo.io/firewall-category: fabric
    networking.liqo.io/firewall-subcategory: all-nodes
spec:
  table:
    family: IPV4
    name: test-table
    chains:
      - hook: forward
        name: test-chain
        policy: accept
        priority: 0
        type: filter
        rules:
          filterRules:
            - action: reject
              match:
                - ip:
                    position: dst
                    value: "10.200.1.11"
                  op: eq
