apiVersion: v1
kind: Namespace
metadata:
  name: rome-local
---
apiVersion: v1
kind: Pod
metadata:
  name: p1
  namespace: rome-local
  labels:
    app: p1
spec:
  containers:
    - name: tester
      image: riccardotornesello/hello-world-http-server:v1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: web
      env:
        - name: IDENTIFIER
          value: p1
---
apiVersion: v1
kind: Service
metadata:
  name: s1
  namespace: rome-local
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
  selector:
    app: p1
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: p2
  namespace: rome-offloaded
  labels:
    app: p2
spec:
  containers:
    - name: tester
      image: riccardotornesello/hello-world-http-server:v1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: web
      env:
        - name: IDENTIFIER
          value: p2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: liqo.io/type
                operator: NotIn
                values:
                  - virtual-node
---
apiVersion: v1
kind: Service
metadata:
  name: s2
  namespace: rome-offloaded
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
  selector:
    app: p2
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: p3
  namespace: rome-offloaded
  labels:
    app: p3
spec:
  containers:
    - name: tester
      image: riccardotornesello/hello-world-http-server:v1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: web
      env:
        - name: IDENTIFIER
          value: p3
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: liqo.io/type
                operator: NotIn
                values:
                  - virtual-node
---
apiVersion: v1
kind: Pod
metadata:
  name: p4
  namespace: rome-offloaded
  labels:
    app: p4
spec:
  containers:
    - name: tester
      image: riccardotornesello/hello-world-http-server:v1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: web
      env:
        - name: IDENTIFIER
          value: p4
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: liqo.io/type
                operator: In
                values:
                  - virtual-node
---
apiVersion: v1
kind: Pod
metadata:
  name: p5
  namespace: rome-offloaded
  labels:
    app: p5
spec:
  containers:
    - name: tester
      image: riccardotornesello/hello-world-http-server:v1.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: web
      env:
        - name: IDENTIFIER
          value: p5
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: liqo.io/type
                operator: In
                values:
                  - virtual-node
