---
- name: Playbook di configurazione per Ubuntu 24.04
  hosts: all
  become: yes
  tasks:
    # ----------------------------------------------------------------
    # HOSTNAME CONFIGURATION
    # ----------------------------------------------------------------
    - name: Set hostname from inventory file
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update localhost entry with new hostname in /etc/hosts
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+ubuntu-24.*$'
        replace: "127.0.1.1 {{ inventory_hostname }}"

    # ----------------------------------------------------------------
    # MACHINE ID CONFIGURATION
    # ----------------------------------------------------------------
    - name: Remove existing machine-id file
      ansible.builtin.file:
        path: /etc/machine-id
        state: absent

    - name: Generate a new machine-id
      ansible.builtin.command: systemd-machine-id-setup
      args:
        creates: /etc/machine-id

    # # ----------------------------------------------------------------
    # # CONFIGURATION OF HOSTS FILE
    # # ----------------------------------------------------------------
    # - name: Add inventory hosts to /etc/hosts
    #   ansible.builtin.blockinfile:
    #     path: /etc/hosts
    #     block: |
    #       {% for host in groups['all'] %}
    #       {{ hostvars[host]['ansible_host'] }} {{ hostvars[host]['inventory_hostname'] }}
    #       {% endfor %}
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK"

    # ----------------------------------------------------------------
    # SYSCTL CONFIGURATION
    # ----------------------------------------------------------------
    - name: Create sysctl configuration for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: "0644"

    - name: Reload sysctl to apply Kubernetes configuration
      ansible.builtin.command: sysctl --system

    # ----------------------------------------------------------------
    # KUBERNETES INSTALLATION
    # ----------------------------------------------------------------
    - name: Disable swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Comment the swap line in /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: "^(.*swap.*)$"
        replace: '# \1'

    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Create configuration directory for containerd
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: "0755"

    - name: Generate default configuration for containerd
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Enable SystemdCgroup in containerd
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: "SystemdCgroup = false"
        replace: "SystemdCgroup = true"

    - name: Restart and enable containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Install necessary packages for Kubernetes repository
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    - name: Add GPG key for Kubernetes repository
      ansible.builtin.shell: >
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubelet, kubeadm, and kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Block the versions of kubelet, kubeadm, and kubectl
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable and start kubelet service
      ansible.builtin.systemd:
        name: kubelet
        enabled: yes
        state: started

    # ----------------------------------------------------------------
    # LIQOCTL INSTALLATION
    # ----------------------------------------------------------------
    - name: Download and extract liqoctl
      ansible.builtin.unarchive:
        src: "https://github.com/liqotech/liqo/releases/download/v1.0.1/liqoctl-linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes
        creates: /tmp/liqoctl

    - name: Install liqoctl in /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/liqoctl
        dest: /usr/local/bin/liqoctl
        owner: root
        group: root
        mode: "0755"
        remote_src: yes

    # ----------------------------------------------------------------
    # CONTROL-PLANE SPECIFIC CONFIGURATION
    # ----------------------------------------------------------------
    - name: Copy kubeadm configuration file to control-plane node
      ansible.builtin.template:
        src: assets/kubeadm-config.yaml
        dest: /root/kubeadm-config.yaml
      when: inventory_hostname in groups['controlplane']

    - name: Copy calico configuration file to control-plane node
      ansible.builtin.copy:
        src: assets/calico-config.yaml
        dest: /root/calico-config.yaml
      when: inventory_hostname in groups['controlplane']
